- include_tasks: "../../lephare.ansible-deploy/config/steps/cachetool.yml"
  when: lephare_cachetool_enable

- include_tasks: "../../lephare.ansible-deploy/config/steps/install_crontab.yml"
  when: lephare_crontab_install

- include_tasks: "../../lephare.ansible-deploy/config/steps/invalidate_cloudfront.yml"
  when: lephare_cloudfront_invalidate

- include_tasks: "../../lephare.ansible-deploy/config/steps/rollbar_notify.yml"
  when: lephare_rollbar_notify

- include_tasks: "../../lephare.ansible-deploy/config/steps/sentry_notify.yml"
  when: lephare_sentry_notify

- include_tasks: "../../lephare.ansible-deploy/config/steps/notify_slack.yml"
  when: lephare_slack_notify
