- include_tasks: "../../lephare.ansible-deploy/config/steps/opcache_clear.yml"
  when: lephare_cachetool_opcache_reset

- include_tasks: "../../lephare.ansible-deploy/config/steps/rollbar_notify.yml"
  when: lephare_rollbar_notify

- include_tasks: "../../lephare.ansible-deploy/config/steps/install_crontab.yml"
  when: lephare_crontab_install

- include_tasks: "../../lephare.ansible-deploy/config/steps/invalidate_cloudfront.yml"
  when: lephare_cloudfront_invalidate
