- include_tasks: "../../lephare.ansible-deploy/config/steps/publish_assets.yml"
  when: lephare_assets_publish

- include_tasks: "../../lephare.ansible-deploy/config/steps/prevent_indexation.yml"
  when: lephare_prevent_robots_indexation

- include_tasks: "../../lephare.ansible-deploy/config/steps/secure.yml"
  when: lephare_http_basic_secure

