- name: 'Invalidate Cloudfront cache'
  command: aws cloudfront create-invalidation --distribution-id {{ lephare_cloudfront_distribution_id }} --paths "{{ item }}"
  with_items: " {{ lephare_cloudfront_path }}"

