- name: Notify Slack channel deploy
  uri:
    url: "{{ notify_slack_deploy_webhook_url }}"
    method: POST
    body: |
      {"channel": "#{{ notify_slack_deploy_channel }}", "username": "{{ notify_slack_deploy_username }}", "text": "Déploiement vers {{ application_environment }} terminé", "icon_emoji": ":rocket:"}
