- name: LEPHARE - Prevent Robots indexation
  copy:
    content: |
        User-agent: *
        Disallow: /

        User-agent: LinkChecker
        Allow: /
    dest: "{{ lephare_document_root_path }}/robots.txt"
