- name: LEPHARE - Prevent Robots indexation
  copy:
    content: |
        User-agent: *
        Disallow: /

        User-agent: LinkChecker
        Allow: /
    dest: "{{ ansistrano_release_path.stdout }}/web/robots.txt"
