- name: LEPHARE - notify Rollbar
  rollbar_deployment:
    token: "{{ lephare_rollbar_token }}"
    environment: "{{ application_environment|default(lephare_rollbar_environment) }}"
    user: ansible
    revision: "{{ ansistrano_git_result.after }}"
