- name: LEPHARE - Sentry - Create release
  uri:
    url: "https://sentry.io/api/0/organizations/le-phare/releases/"
    method: POST
    body_format: json
    status_code: "201,208"
    headers:
      Authorization: "Bearer {{ lephare_sentry_token }}"
    body: |
      {
        "version": "{{ ansistrano_git_result.after|truncate(7, true, '') }}", 
        "projects": ["{{ lephare_sentry_project }}"], 
        "refs": [
          {
            "repository": "{{ lephare_sentry_repository }}",
            "commit": "{{ ansistrano_git_result.after }}",
            "previousCommit": "{{ ansistrano_git_result.before }}"
          }
        ]
      }
  register: sentry_create_release_result
  changed_when: sentry_create_release_result.status == 201
  when: ansistrano_git_result.after != ansistrano_git_result.before
  ignore_errors: True

- name: LEPHARE - Sentry - Notify deploy
  uri:
    url: "https://sentry.io/api/0/organizations/le-phare/releases/{{ ansistrano_git_result.after|truncate(7, true, '') }}/deploys/"
    method: POST
    body_format: json
    status_code: "201"
    headers:
      Authorization: "Bearer {{ lephare_sentry_token }}"
    body: |
      {"environment": "{{ lephare_sentry_environment|default(application_environment) }}"}
  when: 
    - sentry_create_release_result is succeeded 
    - sentry_create_release_result.status == 201
  ignore_errors: True
