- name: LEPHARE - Setup directory permissions for var/logs
  file:
    path: "{{ item }}"
    state: directory
    mode: "{{ lephare_permission_chmod }}"
    recurse: true
  with_items: " {{ lephare_permission_writeable_dirs }}"
