- name: get latest commit message
  shell: 'git log {{ ansistrano_git_branch }} --pretty="%s" -n1'
  args:
    chdir: "{{ ansistrano_deploy_to }}/{{ ansistrano_repo_dir }}"
  register: latest_commit_message

- name: Notify Slack channel deploy
  slack:
    token: "{{ lephare_slack_notify_token }}"
    channel: "{{ lephare_slack_notify_channel }}"
    username: "{{ lephare_slack_notify_username }}"
    msg: "Déploiement vers *{{ application_environment }}* terminé\n> {{ latest_commit_message.stdout }}"
    icon_emoji: ":rocket:"
    color: good

