- name: Notify Slack channel deploy
  slack:
    token: '{{ lephare_slack_notify_token }}'
    msg: 'Déploiement vers {{ application_environment }} terminé'
    channel: '#{{ lephare_slack_notify_channel }}'
    username: 'Ansible on {{ inventory_hostname }}'
    icon_emoji:  ':rocket:'
