- name: Notify Slack channel deploy
  slack:
    token: "{{ lephare_slack_notify_token }}"
    channel: "{{ lephare_slack_notify_channel }}"
    username: "{{ lephare_slack_notify_username }}"
    msg: "Déploiement vers {{ application_environment }} terminé. {{ latest_commit_message }}"
    icon_emoji: ":rocket:"
    color: good

