- name: get latest commit message
  shell: 'git log {{ ansistrano_git_branch }} --pretty="%s" -n1'
  args:
    chdir: "{{ ansistrano_deploy_to }}/{{ ansistrano_repo_dir }}"
  register: latest_commit_message

- name: get latest commit author
  shell: 'git log {{ ansistrano_git_branch }} --pretty="%an" -n1'
  args:
    chdir: "{{ ansistrano_deploy_to }}/{{ ansistrano_repo_dir }}"
  register: latest_commit_author

- name: Notify Slack channel deploy
  slack:
    token: "{{ lephare_slack_notify_token }}"
    channel: "{{ lephare_slack_notify_channel }}"
    username: "{{ lephare_slack_notify_username }}"
    icon_url: "{{ lephare_slack_notify_icon_url }}"
    attachments:
      - pretext: Déploiement terminé
        fallback: "{{ inventory_hostname }} - Déploiement en {{ application_environment }} terminé"
        fields:
          - title: Environnement
            value: "{{ application_environment|capitalize }}"
            short: True
          - title: Release
            value: "{{ ansistrano_git_result.after|truncate(7, True, '') }}"
            short: True
          - title: Dernière modification
            value: "`{{ latest_commit_message.stdout }}` par _{{ latest_commit_author.stdout }}_"
        actions:
          - type: button
            text: Voir le site
            url: "{{ lephare_cachetool_scheme }}://{{ inventory_hostname }}"
            style: primary


