name: Build Ansible docker images

on:
  schedule:
    - cron: "0 12 * * SUN" # every sunday
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  Ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch/tag name
        id: extract_branch
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF/refs\/*\/})" >> $GITHUB_OUTPUT

      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: .

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: lephare/ansible
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        id: docker_build
        with:
          context: docker
          file: ./docker/Dockerfile
          build-args: |
            ANSIBLE_DEPLOY_BRANCH=${{ steps.extract_branch.outputs.branch }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
